"""fix the name fo plan_id to price_id

Revision ID: 340e7aee7ed5
Revises: a819a117d9a8
Create Date: 2025-06-22 09:55:19.792507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340e7aee7ed5'
down_revision = 'a819a117d9a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price_id', sa.String(), nullable=False))
    op.drop_column('subscriptions', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'price_id')
    # ### end Alembic commands ###
