"""adding quantity for day subscription

Revision ID: 4d1e08ae53ed
Revises: 340e7aee7ed5
Create Date: 2025-06-28 14:10:33.398508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1e08ae53ed'
down_revision = '340e7aee7ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('center_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'center_quantity')
    # ### end Alembic commands ###
