"""adding confirmation to user

Revision ID: 4fd205bf13f8
Revises: 4d1e08ae53ed
Create Date: 2025-06-28 22:17:05.116827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd205bf13f8'
down_revision = '4d1e08ae53ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_confirmed'), 'users', ['confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_confirmed'), table_name='users')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
