"""adding the email confirmation table

Revision ID: 5085104e3f99
Revises: 4fd205bf13f8
Create Date: 2025-06-29 02:30:09.540408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5085104e3f99'
down_revision = '4fd205bf13f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_confirmations_id'), 'email_confirmations', ['id'], unique=False)
    op.create_index(op.f('ix_email_confirmations_token'), 'email_confirmations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_confirmations_token'), table_name='email_confirmations')
    op.drop_index(op.f('ix_email_confirmations_id'), table_name='email_confirmations')
    op.drop_table('email_confirmations')
    # ### end Alembic commands ###
