"""adding a role to org user enum

Revision ID: 5e66cffecae8
Revises: 46bd60313c63
Create Date: 2025-08-29 02:39:39.039543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5e66cffecae8'
down_revision = '46bd60313c63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add MODERATOR value to existing enum type
    op.execute("ALTER TYPE organizationrole ADD VALUE 'MODERATOR'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove MODERATOR value from enum type (this is tricky in PostgreSQL)
    # We'll need to recreate the enum without MODERATOR
    op.execute("CREATE TYPE organizationrole_new AS ENUM ('ADMIN', 'MEMBER')")
    op.execute("ALTER TABLE organization_users ALTER COLUMN role TYPE organizationrole_new USING role::text::organizationrole_new")
    op.execute("DROP TYPE organizationrole")
    op.execute("ALTER TYPE organizationrole_new RENAME TO organizationrole")
    
    # ### end Alembic commands ###