"""removed center count from the subscription

Revision ID: 636f67d40d3c
Revises: 863cd17f6e3a
Create Date: 2025-08-21 08:40:18.616732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636f67d40d3c'
down_revision = '863cd17f6e3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'center_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('center_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
