"""adding table for password reset

Revision ID: 863cd17f6e3a
Revises: 5085104e3f99
Create Date: 2025-06-30 13:36:28.514996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863cd17f6e3a'
down_revision = '5085104e3f99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_password_requests_id'), 'reset_password_requests', ['id'], unique=False)
    op.create_index(op.f('ix_reset_password_requests_token'), 'reset_password_requests', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_password_requests_token'), table_name='reset_password_requests')
    op.drop_index(op.f('ix_reset_password_requests_id'), table_name='reset_password_requests')
    op.drop_table('reset_password_requests')
    # ### end Alembic commands ###
