"""moved stripe customer id to org

Revision ID: a819a117d9a8
Revises: e8068f3c0676
Create Date: 2025-06-21 08:34:54.474689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a819a117d9a8'
down_revision = 'e8068f3c0676'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['stripe_customer_id'])
    op.drop_constraint(op.f('users_stripe_customer_id_key'), 'users', type_='unique')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_stripe_customer_id_key'), 'users', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###
