"""adding org owner to oragnization model

Revision ID: e0811fcfd988
Revises: 3766cf4146f8
Create Date: 2025-09-21 07:50:36.821653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0811fcfd988'
down_revision = '3766cf4146f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('org_owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organizations', 'users', ['org_owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'org_owner')
    # ### end Alembic commands ###
